name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up C++ compiler
      run: sudo apt-get install g++ # Asigură-te că g++ este instalat

    - name: Build project
      run: make

    - name: Clean build files
      run: make clean
